# Generated by Django 2.1.2 on 2018-10-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=200)),
                ('PointID', models.CharField(max_length=200)),
                ('Value', models.CharField(max_length=200)),
                ('Flags', models.CharField(max_length=200)),
                ('TimeTag', models.CharField(max_length=200)),
                ('DataType', models.CharField(max_length=200)),
            ],
        ),
    ]
