# Generated by Django 2.1.2 on 2018-10-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genpntdatatable',
            fields=[
                ('tagname', models.CharField(db_column='TagName', max_length=100)),
                ('pointid', models.FloatField(db_column='PointID', primary_key=True, serialize=False)),
                ('value', models.FloatField(db_column='Value')),
                ('flags', models.BigIntegerField(db_column='Flags')),
                ('timetag', models.BigIntegerField(db_column='TimeTag')),
                ('datatype', models.IntegerField(blank=True, db_column='DataType', null=True)),
            ],
            options={
                'db_table': 'GenPntDataTable',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='GenPoint',
        ),
    ]
